services:
  django:
    container_name: "django-admin"
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile_py
    ports:
      - "8000:8000"
    restart: "always"
    entrypoint: python3 manage.py runserver 0.0.0.0:8000

  go:
    container_name: "go-backend"
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile_go
    ports:
      - "8080:8080"
    entrypoint: /app/cmd/main
    restart: "always"
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: "db"
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
        test: pg_isready -U postgres
        interval: 2s
        timeout: 5s
        retries: 10

volumes:
  pgdata: